### ISSUE TITLE
在svn中diff的Excel表格的字段太多的表格就会直接显示不出来，请问怎么解决这个问题

### ISSUE THREAD

**Issue by Fowver** [luxuia/ExcelMerge#6]
![Dingtalk_20240124212646](https://github.com/luxuia/JustDiff/assets/56448880/cfff90d8-2a34-49d7-a72b-2a2e4fc3d357)

在svn中diff的Excel表格的字段太多的表格就会直接显示不出来，请问怎么解决这个问题

**Comment by Fowver** [comment]
![Dingtalk_20240124212646](https://github.com/luxuia/JustDiff/assets/56448880/2d14aa66-10e9-40ad-912a-e1849b3bd8d6)

**Comment by luxuia** [comment]
能提供下对比的两个文件版本么？

**Comment by Fowver** [comment]
感谢大佬，用最新版本后，字段太多对比无法显示的问题解决了
